### ISSUE TITLE
Problems with UTM version 9.501

### ISSUE THREAD

**Issue by airathere** [dmueller4/check_red_state#2]
Hi Daniel,

i have tried your script (first time) to check RED 15 with it.
My problem is the following:

loginuser@nagios:~$ ./check_utm_red_state.sh -H 192.168.1.1 -R A3501xxxx -v -d
 connect to firewall (192.168.1.1) successful
 detected UTM servion:  9.501005

RED STATE CRITICAL - unable to connect to firewall or file not found

Login to UTM and check some things results in:

 loginuser@utm:/home/login > ps ax | grep A3501xxxx | grep -Eo '([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})'
loginuser@utm:/home/login > 

- no results at all

loginuser@utm:/home/login > ps axo '%p%t%a' | grep A3501xxxx
14190  1-21:18:11 A3501xxxx (1) [xx.xx.xx.xx]    <- correct IP is shown here
18970       00:00 grep A3501xxxx

- some result which seem to be OK

So i'm lost here.
Maybe i have done something wrong (?) or your script do not work with 9.5?

Can you help?

Kind regards 
Joe

**Comment by dmueller4** [comment]
Hi Joe,

I'll look into it, just give me a couple days. Maybe I find some time this weekend to test with the current version.

**Comment by dmueller4** [comment]
Hi Joe,

just did i quick check. It seems to work with the UTM 9.5x

Can you please check your RED ID. If ID is wrong you get the error
RED STATE CRITICAL - unable to connect to firewall or file not found

Here's what I got as output:

root@S:/tmp# ./check_utm_red_state.pl -H 192.168.1.1 -R A3501... -v -d
 connect to firewall (192.168.1.1) successful
 detected UTM servion:  9.501005

 connect to firewall (192.168.1.1) successful
 file info /tmp/red_state_A3501...  time: 16:09  date: 2017-06-30

An manually opened connection with the users works. You were not ask for a password and the cmd prompt from the firewall opens? 
If you try like this:
loginuser@nagios:~$# ssh loginuser@192.168.1.1

Regards 
Daniel

**Comment by airathere** [comment]
I doublechecked it - i have for sure the correct RED ID but the heck-script still does not work:

**loginuser@nagios:~$ ./check_utm_red_state.sh -H 192.168.1.1 -R A3501ABC1A2B345 -v -d**
 connect to firewall (192.168.1.1) successful
 detected UTM servion:  9.501005

RED CRITICAL - unable to connect to firewall or file not found

**loginuser@nagios:~$ ssh 192.168.1.1**
Last login: Fri Jun 30 09:34:12 2017 from raspi.mydomain.local

Sophos UTM
(C) Copyright 2000-2017 Sophos Limited and others. All rights reserved.
Sophos is a registered trademark of Sophos Limited and Sophos Group.
All other product and company names mentioned are trademarks or registered
trademarks of their respective owners.

For more copyright information look at /doc/astaro-license.txt
or http://www.astaro.com/doc/astaro-license.txt

NOTE: If not explicitly approved by Sophos support, any modifications
      done by root will void your support.

**loginuser@utm:/home/login > ps axo '%p%t%a' | grep A3501ABC1A2B345**
14190  4-22:24:02 A3501ABC1A2B345 (1) [1.2.3.4]
27086       00:00 grep A3501ABC1A2B345

As you can see, the "ps axo ..." shows an attached RED, with my given ID and the (correct) IP address.
Executing the check-script results in error.

Maybe i can show you via remote session (I don't wanna give the real IP and ID here...)?

Greetz,
Joe

**Comment by dmueller4** [comment]
Hi Joe,

what linux disto are you using?
It seams to fail at the file download. The scp program is available on your system.
please try: scp loginuser@192.168.1.1:/tmp/.build /tmp

I'll update the error checking  and maybe some pre checks this evening.

A remote session maybe a good idea, you can send me an email with the infos.

**Comment by airathere** [comment]
loginuser@nagios:~$ scp loginuser@192.168.1.1:/tmp/.build/ /tmp
.build                                                                                                                                                             
                                                                                                                        100%   47     0.1KB/s   00:00
loginuser@nus-response:~$ ls -la /tmp/.build
-rw-r--r-- 1 loginuser loginuser 47 Jul  3 13:16 .build

The scp itself works without a problem (or should there been some files/dirs more, because: -> there is no file ?)

If i take a look at the UTM box:

loginuser@utm:/home/login > ls -la /tmp/.build
-rw-r--r-- 1 root root 47 Oct 21  2016 /tmp/.build

There is no file too...

I'm currently using Rasbian 7.2 on a RasPi 3, scp is available (see before)

**Comment by airathere** [comment]
We can use AnyDesk or Teamviewer Session. Which is preferred? When?

Vom iPhone gesendet, daher bitte ich, Schreibfehler und Abkürzungen zu entschuldigen.

**Comment by dmueller4** [comment]
Teamviewer is fine, 16:30
You can send me the ID to daniel.mueller @ cobotec.de

**Comment by dmueller4** [comment]
Update is now available.
On the website I found references to nagios as plugin api and core.
So you should use the nagios version of the check. 
I hope it'll works ;-)
